# ── MediaPipe LLM Inference ──────────────────────────────────────────────────
# MediaPipe's native C++ code calls Java methods via JNI by exact name.
# R8 must NOT rename or remove these classes/methods in release builds.

-keep class com.google.mediapipe.** { *; }
-keepclassmembers class com.google.mediapipe.** { *; }

# Keep all JNI callback interfaces (onAsyncResponse, etc.)
-keepclasseswithmembernames class * {
    native <methods>;
}

# Keep any class that has a method called onAsyncResponse (JNI callback target)
-keepclassmembers class * {
    void onAsyncResponse(byte[]);
    void onAsyncResponse(...);
}

# Keep MediaPipe tasks-genai specific classes
-keep class com.google.mediapipe.tasks.genai.** { *; }
-keepclassmembers class com.google.mediapipe.tasks.genai.** { *; }

# Keep MediaPipe core
-keep class com.google.mediapipe.framework.** { *; }
-keepclassmembers class com.google.mediapipe.framework.** { *; }

# Keep TFLite classes (used internally by MediaPipe)
-keep class org.tensorflow.lite.** { *; }
-keepclassmembers class org.tensorflow.lite.** { *; }

# ── Flutter ──────────────────────────────────────────────────────────────────
-keep class io.flutter.** { *; }
-keep class io.flutter.plugin.** { *; }
-keep class io.flutter.embedding.** { *; }

# ── General JNI safety ───────────────────────────────────────────────────────
# Prevent stripping of any class loaded via JNI reflection
-keepattributes *Annotation*
-keepattributes Signature
-keepattributes Exceptions

# ── Auto-generated by Gradle (missing_rules.txt) ─────────────────────────────
# Flutter uses Play Core split-install APIs optionally; suppress warnings since
# we don't ship to the Play Store with dynamic delivery.
-dontwarn com.google.android.play.core.splitcompat.SplitCompatApplication
-dontwarn com.google.android.play.core.splitinstall.SplitInstallException
-dontwarn com.google.android.play.core.splitinstall.SplitInstallManager
-dontwarn com.google.android.play.core.splitinstall.SplitInstallManagerFactory
-dontwarn com.google.android.play.core.splitinstall.SplitInstallRequest$Builder
-dontwarn com.google.android.play.core.splitinstall.SplitInstallRequest
-dontwarn com.google.android.play.core.splitinstall.SplitInstallSessionState
-dontwarn com.google.android.play.core.splitinstall.SplitInstallStateUpdatedListener
-dontwarn com.google.android.play.core.tasks.OnFailureListener
-dontwarn com.google.android.play.core.tasks.OnSuccessListener
-dontwarn com.google.android.play.core.tasks.Task
# MediaPipe image classes referenced by LLM API but not needed for text-only inference
-dontwarn com.google.mediapipe.framework.image.BitmapExtractor
-dontwarn com.google.mediapipe.framework.image.ByteBufferExtractor
-dontwarn com.google.mediapipe.framework.image.MPImage
-dontwarn com.google.mediapipe.framework.image.MPImageProperties
-dontwarn com.google.mediapipe.framework.image.MediaImageExtractor
